arch:
  - ppc64le
  - s390x
  - arm64
os: linux
language: python

before_install:
  - sudo apt-get --yes install libgeos-dev
  - pip install numpy cython

install:
  - pip install . --no-deps

script:
  - pytest --doctest-modules
