language: python

matrix:
  include:
  - os: linux
    dist: xenial
    python: "3.6"
    addons:
      apt:
        packages:
          - libgeos-dev
    before_install:
      - pip install numpy
  - os: linux
    dist: xenial
    python: "3.6"
    before_install:
      - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
      - bash miniconda.sh -b -p "$HOME"/miniconda
      - source "$HOME"/miniconda/etc/profile.d/conda.sh
      - conda update --yes conda
      - conda create -n testenv --yes pip numpy geos pytest python=$TRAVIS_PYTHON_VERSION
  - os: osx
    python: "3.6"
    before_install:
      - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
      - bash miniconda.sh -b -p "$HOME"/miniconda
      - source "$HOME"/miniconda/etc/profile.d/conda.sh
      - conda update --yes conda
      - conda create -n testenv --yes pip numpy geos pytest python=$TRAVIS_PYTHON_VERSION

install:
  - python setup.py build_ext --inplace
  - pip install .[test]

script: pytest
