os: linux
dist: focal
language: python
python: "3.8"

env:
  - GEOS_VERSION=3.10.1

cache:
  directories:
    - $HOME/geosinstall
    - ~/.cache/pip

matrix:
  include:
    - arch: ppc64le
    - arch: s390x
    - arch: arm64
    - arch: arm64
      services: docker
      env:
        - CIBUILDWHEEL=1
        - CIBW_SKIP="pp*"
        - CIBW_ENVIRONMENT_LINUX="GEOS_VERSION=3.10.1 
                                 GEOS_INSTALL=/host/home/travis/geos-3.10.1
                                 GEOS_CONFIG=/host/home/travis/geos-3.10.1/bin/geos-config
                                 LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/host/home/travis/geos-3.10.1/lib"
        - CIBW_BEFORE_ALL="./ci/install_geos.sh"
        - CIBW_TEST_REQUIRES="pytest"
        - CIBW_TEST_COMMAND="pytest --pyargs pygeos.tests"

  allow_failures:
    - arch: s390x

branches:
  only:
  - master
  - travis

install:
  - |
    if [[ -z $CIBUILDWHEEL ]]; then
      export GEOS_INSTALL=$HOME/geosinstall/geos-$GEOS_VERSION;
      ./ci/install_geos.sh;
      export GEOS_CONFIG=$HOME/geosinstall/geos-$GEOS_VERSION/bin/geos-config;
      then pip install .[test];
    else
      python3 -m pip install cibuildwheel==2.3.0;
    fi

script:
  - |
    if [ -z $CIBUILDWHEEL ]; then
      pytest pygeos;
    else
      python3 -m cibuildwheel --output-dir wheelhouse;
    fi

deploy:
  provider: pypi
  username: "__token__"
  skip_cleanup: true
  on:
    tags: true
  password:
    secure: "" # Set to an encrypted API token. See https://docs.travis-ci.com/user/deployment/pypi/
