language: minimal

matrix:
  include:
  - os: linux
    env: DEPS="python=3.5 numpy=1.11 geos=3.6.0"
  - os: linux
    env: DEPS="python=3.6 numpy=1.14 geos=3.6.2"
  - os: linux
    env: DEPS="numpy geos"
  - os: osx
    env: DEPS="numpy geos"

before_install:
  # obtain miniconda installer
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    elif  [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi;

install:
  # install miniconda
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda:$HOME/miniconda/bin:$PATH"
  # for conda version 4.4 or later
  - source $HOME/miniconda/etc/profile.d/conda.sh
  - hash -r;
  - conda config --set always_yes yes --set changeps1 no;
  - conda update -q conda;
  - conda create -n testenv pytest $DEPS;
  - conda activate testenv;
  - conda --version ; python --version ; pip --version;
  - python setup.py build_ext --inplace
  - pip install .[test]

script: pytest --black
