---
language: python
dist: xenial
os: linux

cache:
  directories:
    - $HOME/geosinstall
    - ~/.cache/pip

jobs:
  include:
    - python: "3.5"
      env:  # 2015
        GEOS_VERSION="3.5.2"
        NUMPY_VERSION="1.10.4"
    - python: "3.6"
      env:  # 2017
        GEOS_VERSION="3.6.4"
        NUMPY_VERSION="1.13.3"
    - python: "3.7"
      env:  # 2018
        GEOS_VERSION="3.7.3"
        NUMPY_VERSION="1.15.4"
    - python: "3.8"
      env:  # 2019
        GEOS_VERSION="3.8.1"
        NUMPY_VERSION="1.17.5"
    - python: "3.9"
      env:  # 2020
        GEOS_VERSION="3.8.1"
        NUMPY_VERSION="1.19.4"
    - python: "3.9-dev"
      env: GEOS_VERSION="master"
  allow_failures:
    - python: "3.9-dev"
      env: GEOS_VERSION="master"

install:
  - export GEOS_INSTALL=$HOME/geosinstall/geos-$GEOS_VERSION
  - ./ci/install_geos.sh
  - cd $TRAVIS_BUILD_DIR
  - pip install --disable-pip-version-check --upgrade pip
  - pip install --upgrade wheel
  - if [ "$GEOS_VERSION" = "master" ]; then
      pip install --upgrade --pre Cython numpy pytest;
    else
      pip install --upgrade Cython "numpy==$NUMPY_VERSION" pytest;
    fi
  - export LD_LIBRARY_PATH=$GEOS_INSTALL/lib
  - export PATH=$GEOS_INSTALL/bin:$PATH
  - python setup.py build_ext --inplace
  - pip install --no-deps -e .

script:
  - pytest --doctest-modules
