arch:
  - ppc64le
  - s390x
  - arm64
os: linux
dist: focal
language: python
python: "3.8"

before_install:
  - sudo apt-get --yes install libgeos-dev
  - pip install numpy cython

install:
  - pip install . --no-deps

script:
  - pytest --doctest-modules
