[build-system]
# numpy and Cython are required to execute setup.py to build Cython extensions
requires = [
    "setuptools",
    "wheel",
    "numpy==1.13.3; python_version=='3.6' and platform_machine != 'aarch64'",
    "numpy==1.19.3; python_version=='3.6' and platform_machine == 'aarch64'",
    "numpy==1.14.5; python_version=='3.7' and platform_machine != 'aarch64'",
    "numpy==1.19.3; python_version=='3.7' and platform_machine == 'aarch64'",
    "numpy==1.17.3; python_version=='3.8' and platform_machine != 'aarch64' and platform_machine != 'arm64'",
    "numpy==1.19.3; python_version=='3.8' and platform_machine == 'aarch64'",
    "numpy==1.21.3; python_version=='3.8' and platform_machine == 'arm64'",
    "numpy==1.19.3; python_version=='3.9' and platform_machine != 'arm64'",
    "numpy==1.21.3; python_version=='3.9' and platform_machine == 'arm64'",
    "numpy==1.21.3; python_version=='3.10'",
    # do not pin numpy on future versions of python to avoid incompatible numpy and python versions
    "numpy; python_version>='3.11'",
    "Cython>=0.29",
]
