[build-system]
# numpy and Cython are required to execute setup.py to build Cython extensions
requires = [
    "Cython~=0.29",
    "oldest-supported-numpy",
    "setuptools>=61.0.0",
]
build-backend = "setuptools.build_meta"
