name: pygeos
channels:
  - conda-forge
dependencies:
  - python==3.8.*
  - geos==3.8.*
  - numpy==1.19.*
  - numpydoc==1.1.*
  - Cython==0.29.*
  # include those here to ensure we get the latest versions
  - sphinx
  - sphinx_rtd_theme
