name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install flake8, isort and black
        run: pip install flake8 isort black

      - name: Run flake8
        run: flake8 pygeos

      - name: Run black
        run: black pygeos --check

      - name: Run isort
        run: isort pygeos --check-only --extend-skip __init__.py
  